
name: Renovate
on:
  schedule:
    # The "*" (#42, asterisk) character has special semantics in YAML, so this
    # string has to be quoted.
    - cron: '0/15 * * * *'
  push:
    branches:
      - main
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v38.1.6
        env: 
          LOG_LEVEL: 'debug'
        with:
          configurationFile: config.js
          token: ${{ secrets.RENOVATE_TOKEN }}
          
